export const profilelang = {
  title: "Profiili",
  details: {
    details: "Tiedot",
    name: "Nimi",
    email: "Sähköposti",
    phone: "Puhelinnumero",
    idnumber: "Henkilötunnus",
    iban: "IBAN",
    city: "Kaupunki",
    birthdate: "Syntymäaika",
    nationality: "Kansalaisuus",
  },
  cards: {
    cards: "Kortit",
    cardtype: "Tyyppi",
    cardend: "Voimassaolo",
    cardimage: "Kuvake",
    uploadcard: "Tallenna",
    uploadcardinfo: "Lataa kortin kuva",
    download: "Lataa kuva",
    delete: "Poista kuva",
    category: "Kategoria",
    owncar: "Auto käytettävissä",
    types: {
      id: "Henkilökorti",
      driving: "Ajokortti",
      passport: "Passi",
      workcard: "Työkortti",
      hygienepass: "Hygieniapassi",
      worksafetypass: "Työturvallisuuskortti",
      fireworkcard: "Tulityökortti",
      electricalsafetypass: "Sähköturvallisuuskortti",
      other: "Muu",
    },
  },
}
